name: Lint frontend

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm --prefix ./frontend install
      - name: Run ESLint
        run: eslint -c ./frontend/.eslintrc.js . --ext .js,.jsx,.ts,.tsx