name: Integration Testing

on: push
#  pull_request:
#    branches: [ master ]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: start appwrite
        working-directory: ./backend/appwrite-config
        run: docker-compose up -d
      - name: create project
        working-directory: ./backend/setup_appwrite
        run: |
          npm i
          node index.js
      - name: show key file 
        working-directory: ./backend/setup_appwrite
        run: |
          ls
          ./init-cli.sh
          create-set-wallet-function.sh
      
