name: Integration Testing

on: push
#  pull_request:
#    branches: [ master ]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd backend/appwrite-config
      - run: docker-compose up -d
      - run: cd ../setup-appwrite
      - run: node index.js
      - run: ls
      
